# 关于中值滤波和均值滤波的一个简单例子

以简单矩阵为例，描述中值滤波、均值滤波的实际计算结果。

对于矩阵$A$、$B$，分别计算中值滤波和均值滤波。

$$
A = \begin{bmatrix}
   5 & 9 & 7 \\
   3 & 3 & 0 \\
   1 & 6 & 2
  \end{bmatrix}
$$

$$
B = \begin{bmatrix}
   5 & 9 & 7 \\
   3 & 12 & 0 \\
   1 & 6 & 2
  \end{bmatrix}  
$$

## 中值滤波

中值滤波是一种非线性滤波技术，它通过取邻域内像素值的中位数来替代中心像素值，从而有效地去除噪声。对于矩阵$A$和$B$，我们可以使用一个3x3的窗口来进行中值滤波。

In [1]:
import cv2
import numpy as np

img_a = np.array([[5, 9, 7],
                  [3, 3, 0],
                    [1, 6, 2]], dtype=np.uint8)

img_b = np.array([[5, 9, 7],
                  [3, 12, 0],
                  [1, 6, 2]], dtype=np.uint8)

blurred_a = cv2.medianBlur(img_a, 3)
blurred_b = cv2.medianBlur(img_b, 3)

img_a, blurred_a, img_b, blurred_b

(array([[5, 9, 7],
        [3, 3, 0],
        [1, 6, 2]], dtype=uint8),
 array([[5, 5, 7],
        [3, 3, 3],
        [3, 2, 2]], dtype=uint8),
 array([[ 5,  9,  7],
        [ 3, 12,  0],
        [ 1,  6,  2]], dtype=uint8),
 array([[5, 7, 7],
        [5, 5, 6],
        [3, 2, 2]], dtype=uint8))

## 均值滤波


In [2]:
mean_blurred_a = cv2.blur(img_a, (3, 3))
mean_blurred_b = cv2.blur(img_b, (3, 3))

img_a, mean_blurred_a, img_b, mean_blurred_b

(array([[5, 9, 7],
        [3, 3, 0],
        [1, 6, 2]], dtype=uint8),
 array([[5, 4, 4],
        [5, 4, 5],
        [3, 2, 3]], dtype=uint8),
 array([[ 5,  9,  7],
        [ 3, 12,  0],
        [ 1,  6,  2]], dtype=uint8),
 array([[9, 6, 8],
        [7, 5, 7],
        [7, 4, 7]], dtype=uint8))